apiVersion: v1
kind: Service
metadata:
  name: {{ include "ratchet.web.fullname" . }}
  labels:
    {{- include "ratchet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.serviceType | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
      {{- if eq (default "ClusterIP" .Values.web.serviceType) "NodePort" }}
      nodePort: {{ .Values.web.nodePort }}
      {{- end }}
  selector:
    app: {{ include "ratchet.web.fullname" . }}
